CREATE DATABASE BOLSAEMPLEO;

USE BOLSAEMPLEO;

CREATE TABLE EMPLEOS(
CODEMP INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE NVARCHAR(75) NOT NULL,
EMPRESA NVARCHAR(75) NOT NULL,
POSICION NVARCHAR(75) NOT NULL,
DESCRIPCION NVARCHAR(150) NOT NULL,
UBICACION NVARCHAR(75) NOT NULL,
TIPO NVARCHAR (50) NOT NULL,
LOGO varbinary(max),
SITIOWEB NVARCHAR (50) NOT NULL,
CORREO NVARCHAR (50) NOT NULL,
FECHA DATETIME NOT NULL,
CATEGORIA NVARCHAR(50),
ESTADO NVARCHAR (50) NOT NULL,
)

INSERT INTO EMPLEOS VALUES
('Soporte Tecnico', 'Software SA', 'Soporte Tecnico', 'Proveer de mantenimento al hardware y software de la empresa', 'Av 27 de Febrero', 'Tiempo completo',
'www.softwaresa.com.do', 'recursoshumanosSoftwareSA@gmail.com','12-05-2021', 'Informatica', 'Activo')